In [2]:
import pandas as pd
import numpy as np

In [3]:
batting_df = pd.read_csv('MLB_batting_stats_ALL_BATTING.csv')
pitching_df = pd.read_csv('MLB_pitching_stats_ALL_PITCHING.csv')
game_df = pd.read_csv('Retro_Baseball.csv')
batting_df.drop(columns = batting_df.columns[0], axis = 1, inplace = True)
pitching_df.drop(columns = pitching_df.columns[0], axis = 1, inplace = True)
game_df.drop(columns = game_df.columns[0], axis = 1, inplace = True)

FileNotFoundError: [Errno 2] No such file or directory: 'Retro_Baseball.csv'

In [ ]:
batting_col_del_2 = ['gidpOpp', 'numberOfPitches', 'pitchesPerPlateAppearance', 'walksPerStrikeout', 'iso', 'walkOffs', 'gamesPlayed', 'caughtStealing', 'stolenBases', 'stolenBasePercentage']
batting_df.drop(batting_col_del_2, axis='columns', inplace=True)
pitching_col_del_2 = ['inheritedRunners', 'inheritedRunnersScored', 'bequeathedRunners', 'bequeathedRunnersScored', 'stolenBases', 'caughtStealing', 'gamesFinished', 'gidpOpp', 'wildPitches', 'balks', 'pickoffs', 'strikePercentage', 'pitchesPerInning', 'pitchesPerPlateAppearance', 'iso', 'gamesPlayed', 'gamesStarted', 'stolenBasePercentage', 'numberOfPitches', 'inningsPitched', 'wins', 'losses', 'saves', 'saveOpportunities', 'holds', 'blownSaves', 'outs', 'gamesPitched', 'completeGames', 'shutouts', 'strikes']
pitching_df.drop(pitching_col_del_2, axis= 'columns', inplace=True)
game_col_del_2 = ['VisitorSH', 'VisitorSF', 'VisitorSB', 'VisitorCS', 'VisitorCI', 'VisitorPitchers', 'VisitorER', 'VisitorWP', 'VisitorBalks', 'VisitorPO', 'VisitorA', 'VisitorE', 'VisitorPassed', 'HomeSH', 'HomeSF', 'HomeSB', 'HomeCS', 'HomeCI', 'HomePitchers', 'HomeER', 'HomeWP', 'HomeBalks', 'HomePO', 'HomeA', 'HomeE', 'HomePassed']
game_df.drop(game_col_del_2, axis='columns', inplace=True)
batting_col_del_3 = ['sacBunts', 'sacFlies', 'reachedOnError', 'gidp', 'babip', 'extraBaseHits', 'hitByPitch', 'walksPerPlateAppearance', 'strikeoutsPerPlateAppearance', 'homeRunsPerPlateAppearance', 'groundOuts', 'airOuts', 'doubles', 'triples', 'homeRuns', 'groundOutsToAirouts', 'atBatsPerHomeRun', ]
batting_df.drop(batting_col_del_3, axis=1, inplace=True)
pitching_col_del_3 = ['battersFaced', 'babip', 'obp', 'slg', 'strikesoutsToWalks', 'qualityStarts', 'doubles', 'triples', 'walksPerPlateAppearance', 'strikeoutsPerPlateAppearance', 'homeRunsPerPlateAppearance', 'walksPerStrikeout', 'groundOuts', 'airOuts', 'runs', 'homeRuns', 'strikeOuts', 'baseOnBalls', 'intentionalWalks', 'hits', 'hitByPitch', 'atBats', 'groundIntoDoublePlay', 'earnedRuns', 'hitBatsmen', 'totalBases', 'groundOutsToAirouts', 'strikeoutWalkRatio', 'sacBunts', 'sacFlies', ]
pitching_df.drop(pitching_col_del_3, axis=1, inplace=True)
game_col_del_3 = ['VisitorD', 'VisitorT', 'VisitorHR', 'VisitorRBI', 'VisitorK', 'VisitorGDP', 'VisitorTER', 'VisitorDB', 'VisitorTP', 'HomeD', 'HomeT', 'HomeHR', 'HomeRBI', 'HomeK', 'HomeGDP', 'HomeTER', 'HomeDB', 'HomeTP', 'VisitorStartingPitcherID', 'HomeStartingPitcherID', 'VisitorBatting1PlayerID', 'VisitorBatting1Name', 'VisitorBatting2PlayerID', 'VisitorBatting2Name', 'VisitorBatting3PlayerID', 'VisitorBatting3Name', 'VisitorBatting4PlayerID', 'VisitorBatting4Name', 'VisitorBatting5PlayerID', 'VisitorBatting5Name', 'VisitorBatting6PlayerID', 'VisitorBatting6Name', 'VisitorBatting7PlayerID', 'VisitorBatting7Name', 'VisitorBatting8PlayerID', 'VisitorBatting8Name', 'VisitorBatting9PlayerID', 'VisitorBatting9Name', 'HomeBatting1PlayerID', 'HomeBatting1Name', 'HomeBatting2PlayerID', 'HomeBatting2Name', 'HomeBatting3PlayerID', 'HomeBatting3Name', 'HomeBatting4PlayerID', 'HomeBatting4Name', 'HomeBatting5PlayerID', 'HomeBatting5Name', 'HomeBatting6PlayerID', 'HomeBatting6Name', 'HomeBatting7PlayerID', 'HomeBatting7Name', 'HomeBatting8PlayerID', 'HomeBatting8Name', 'HomeBatting9PlayerID', 'HomeBatting9Name']
game_df.drop(game_col_del_3, axis=1, inplace=True)

In [ ]:
batting_df.head()

,year,playerId,playerName,type,rank,playerFullName,playerFirstName,playerLastName,playerUseName,playerInitLastName,...,intentionalWalks,hits,avg,atBats,obp,slg,ops,groundIntoDoublePlay,rbi,catchersInterference
0,2020,593160,Whit Merrifield,player,1,Whit Merrifield,Whitley,Merrifield,Whit,W Merrifield,...,0,70,0.282,248,0.325,0.440,0.765,3,30,0
1,2020,547989,José Abreu,player,2,José Abreu,José,Abreu,José,J Abreu,...,1,76,0.317,240,0.370,0.617,0.987,10,60,0
2,2020,621020,Dansby Swanson,player,3,Dansby Swanson,James,Swanson,Dansby,D Swanson,...,0,65,0.274,237,0.345,0.464,0.809,0,35,0
3,2020,596019,Francisco Lindor,player,4,Francisco Lindor,Francisco,Lindor,Francisco,F Lindor,...,2,61,0.258,236,0.335,0.415,0.750,8,27,0
4,2020,596115,Trevor Story,player,5,Trevor Story,Trevor,Story,Trevor,T Story,...,1,68,0.289,235,0.355,0.519,0.874,5,28,0

In [ ]:
pitching_df.head()

,year,playerId,playerName,type,rank,playerFullName,playerFirstName,playerLastName,playerUseName,playerInitLastName,...,lineHits,groundHits,avg,era,whip,winPercentage,strikeoutsPer9Inn,walksPer9Inn,hitsPer9Inn,catchersInterference
0,2020,676886,Jeremy Beasley,player,1,Jeremy Beasley,Jeremy,Beasley,Jeremy,J Beasley,...,2,0,0.667,0.00,6.00,.---,27.00,0.00,54.00,0
1,2020,621532,Anthony Bemboom,player,1,Anthony Bemboom,Anthony,Bemboom,Anthony,A Bemboom,...,0,0,0.000,0.00,1.00,.---,0.00,9.00,0.00,0
2,2020,592145,Jesse Biddle,player,1,Jesse Biddle,Jesse,Biddle,Jesse,J Biddle,...,0,1,0.333,0.00,3.00,.---,13.50,13.50,13.50,0
3,2020,670712,Mike Brosseau,player,1,Mike Brosseau,Michael,Brosseau,Mike,M Brosseau,...,0,0,0.000,0.00,0.00,.---,27.00,0.00,0.00,0
4,2020,543056,Danny Coulombe,player,1,Danny Coulombe,Daniel,Coulombe,Danny,D Coulombe,...,2,0,0.200,0.00,1.88,.---,10.13,10.13,6.75,0

In [ ]:
game_df.head()

,Date,DoubleHeader,DayOfWeek,VisitingTeam,VisitingTeamLeague,VisitingTeamGameNumber,HomeTeam,HomeTeamLeague,HomeTeamGameNumber,VisitorRunsScored,...,HomeBatting2Position,HomeBatting3Position,HomeBatting4Position,HomeBatting5Position,HomeBatting6Position,HomeBatting7Position,HomeBatting8Position,HomeBatting9Position,AdditionalInfo,AcquisitionInfo
0,2023-03-30,0,Thu,MIL,NL,1,CHN,NL,1,0,...,6,7,8,10,2,3,5,9,NaN,Y
1,2023-03-30,0,Thu,PIT,NL,1,CIN,NL,1,5,...,8,10,2,3,9,5,7,6,NaN,Y
2,2023-03-30,0,Thu,ARI,NL,1,LAN,NL,1,2,...,3,2,5,10,7,4,8,6,NaN,Y
3,2023-03-30,0,Thu,NYN,NL,1,MIA,NL,1,5,...,5,3,8,10,9,7,2,6,NaN,Y
4,2023-03-30,0,Thu,COL,NL,1,SDN,NL,1,7,...,7,5,6,3,10,2,4,9,NaN,Y

Batting Feature engineering ideas
All of these stats will be on a PER PLATE APPEARANCE then divide by 162 to get PER GAME STATS
Team stats will be summed up and averaged - Will ultimately be compared to a teams 7 day trends history
'totalBases' / total 'plateAppearances' - DONE
'leftonbase'/ total 'plateAppearances' - DONE
'runs' / total 'plateAppearances' - DONE
'strikeOuts' / total 'atBats' - DONE
'baseOnBalls' + 'intentionalWalks' / total 'plateAppearances' - DONE
'hits' / total 'atBats' --- Leverage for game_df. get team stats per game...
'obp' / # of batters on team --- Same as above
'rbi' / total 'atBats' - DONE

In [ ]:
# MIA & FLO team names are different. Standardizing to MIA
batting_df.replace(to_replace='FLA', value='MIA', inplace=True)

In [ ]:
# THIS IS THE FRAMEWORK TO GENERATE TEAM SEASON STATISTICS...
# Creating a dataframe containing each teams annual Batting Averages

a = batting_df.groupby(['year', 'teamAbbrev'])['hits'].sum()
b = batting_df.groupby(['year', 'teamAbbrev'])['atBats'].sum()
a = a.to_frame()
b = b.to_frame()
BA = a.join(b, on=['year', 'teamAbbrev'])
BA['team_BA'] = round((BA['hits']/BA['atBats']), 3)
# BA = BA.reset_index()

In [ ]:
# Total bases per plate appearance
a = batting_df.groupby(['year', 'teamAbbrev'])['totalBases'].sum()
b = batting_df.groupby(['year', 'teamAbbrev'])['plateAppearances'].sum()
a = a.to_frame()
b = b.to_frame()
TB = a.join(b, on=['year', 'teamAbbrev'])
TB['total_bases_avg'] = round((TB['totalBases']/TB['plateAppearances']), 3)
# TB = TB.reset_index()

In [ ]:
# LOB per plate appearnace

a = batting_df.groupby(['year', 'teamAbbrev'])['leftOnBase'].sum()
b = batting_df.groupby(['year', 'teamAbbrev'])['plateAppearances'].sum()
a = a.to_frame()
b = b.to_frame()
LOB = a.join(b, on=['year', 'teamAbbrev'])
LOB['LOB_avg'] = round((LOB['leftOnBase']/LOB['plateAppearances']), 3)
# LOB = LOB.reset_index()

In [ ]:
# Runs per plate appearance

a = batting_df.groupby(['year', 'teamAbbrev'])['runs'].sum()
b = batting_df.groupby(['year', 'teamAbbrev'])['plateAppearances'].sum()
a = a.to_frame()
b = b.to_frame()
RUNS = a.join(b, on=['year', 'teamAbbrev'])
RUNS['runs_avg'] = round((RUNS['runs']/RUNS['plateAppearances']), 3)
# RUNS = RUNS.reset_index()

In [ ]:
# K's per AtBat

a = batting_df.groupby(['year', 'teamAbbrev'])['strikeOuts'].sum()
b = batting_df.groupby(['year', 'teamAbbrev'])['atBats'].sum()
a = a.to_frame()
b = b.to_frame()
K = a.join(b, on=['year', 'teamAbbrev'])
K['K_avg'] = round((K['strikeOuts']/K['atBats']), 3)
# K = K.reset_index()

In [ ]:
# BB per plate appearance

a = batting_df.groupby(['year', 'teamAbbrev'])['baseOnBalls'].sum()
b = batting_df.groupby(['year', 'teamAbbrev'])['plateAppearances'].sum()
a = a.to_frame()
b = b.to_frame()
BB = a.join(b, on=['year', 'teamAbbrev'])
BB['BB_avg'] = round((BB['baseOnBalls']/BB['plateAppearances']), 3)
# BB = BB.reset_index()

In [ ]:
# RBI per plate appearance

a = batting_df.groupby(['year', 'teamAbbrev'])['rbi'].sum()
b = batting_df.groupby(['year', 'teamAbbrev'])['plateAppearances'].sum()
a = a.to_frame()
b = b.to_frame()
RBI = a.join(b, on=['year', 'teamAbbrev'])
RBI['RBI_avg'] = round((RBI['rbi']/RBI['plateAppearances']), 3)
# RBI = RBI.reset_index()
batting_df.head()

,year,playerId,playerName,type,rank,playerFullName,playerFirstName,playerLastName,playerUseName,playerInitLastName,...,intentionalWalks,hits,avg,atBats,obp,slg,ops,groundIntoDoublePlay,rbi,catchersInterference
0,2020,593160,Whit Merrifield,player,1,Whit Merrifield,Whitley,Merrifield,Whit,W Merrifield,...,0,70,0.282,248,0.325,0.440,0.765,3,30,0
1,2020,547989,José Abreu,player,2,José Abreu,José,Abreu,José,J Abreu,...,1,76,0.317,240,0.370,0.617,0.987,10,60,0
2,2020,621020,Dansby Swanson,player,3,Dansby Swanson,James,Swanson,Dansby,D Swanson,...,0,65,0.274,237,0.345,0.464,0.809,0,35,0
3,2020,596019,Francisco Lindor,player,4,Francisco Lindor,Francisco,Lindor,Francisco,F Lindor,...,2,61,0.258,236,0.335,0.415,0.750,8,27,0
4,2020,596115,Trevor Story,player,5,Trevor Story,Trevor,Story,Trevor,T Story,...,1,68,0.289,235,0.355,0.519,0.874,5,28,0

Merge all Team Stats into one dataframe

In [ ]:
team_stats_lst = [BA, TB, LOB, RUNS, K, BB, RBI]

In [ ]:
team_stats = pd.concat(team_stats_lst, join = 'outer', axis = 1)

In [ ]:
team_stats = team_stats.reset_index()

In [4]:
team_stats.columns
team_stats.head()
team_stats.tail()
type(team_stats['year'])

NameError: name 'team_stats' is not defined

Pitching Feature Ideas:


Pitching stats will focus on starting pitchers Per9 innings stat (except for certain features)

'winningPercentage'

'runsScoredPer9'

'hitsPer9'

'era'

'whip'

In [ ]:
# Rearrange the pitching_df so the columns have a better flow
pitching_df = pitching_df.reindex(columns=['year','playerName','teamAbbrev','winningPercentage','runsScoredPer9','hitsPer9','strikeoutsPer9','baseOnBallsPer9','homeRunsPer9','era','whip','ops','gidp','avg'])

In [ ]:
pitching_df.replace(to_replace='FLA', value = 'MIA', inplace = True)

Game DF Feature ideas:

Turn VisitorRunsScored & HomeRunsScore into a column that indicates if the home team won - DONE.

Combine VisitorHBP & VisitorBB & VisitorIBB into a single column containing all the stats - DONE.

Same with HomeHBP & HomeBB & HomeIBB - DONE.

Combine VisitorH / VisitorAB = team_BA - DONE.
Same with HomeH / HomeAB - DONE.

Eventually add on all the other engineered features into this dataframe...

Since the game_df has a date column, I'd like to leverage that to look at 7-day-trends, 14-day-trends, etc

In [ ]:
# Creating a Target column for the model to eventually train on
game_df['Home_team_won?'] = game_df['HomeRunsScore'] > game_df['VisitorRunsScored']

In [ ]:
# Adding a Home & Away BA per game to compare batting trends over time
game_df['Visitor_BA'] = round((game_df['VisitorH'] / game_df['VisitorAB']), 3)
game_df['Home_BA'] = round((game_df['HomeH'] / game_df['HomeAB']), 3)

In [ ]:
# Creating a new column in order to add Date/Time to my dataframe
game_df['New_Date'] = pd.to_datetime(game_df['Date'], format='%Y-%m-%d')

# game_df['New_Date'] = pd.to_datetime(game_df['Date'].astype(str), format='%Y%m%d')

In [ ]:
# Rearranging columns so new date/time is at the front of the DF & dropping old date column since it was an integer
game_df = game_df.reindex(columns=['New_Date','Date', 'VisitingTeam','VisitorStartingPitcherName','HomeTeam','HomeStartingPitcherName', 'VisitorRunsScored','HomeRunsScore', 'VisitorAB', 'VisitorH','Visitor_BA', 'VisitorHBP', 'VisitorBB','VisitorIBB', 'VisitorLOB', 'HomeAB', 'HomeH', 'Home_BA', 'HomeHBP', 'HomeBB', 'HomeIBB', 'HomeLOB', 'Home_team_won?'])
game_df.drop('Date', axis='columns', inplace=True)

In [ ]:
# Had an extra team due to the Marlins having two different labels. Updating their team name to MIA
game_df.replace(to_replace='FLO', value='MIA', inplace=True)

# Updating game_df so team abbreviations match. Will be leveraged when aggregating teams stats
game_df.replace(to_replace={"NYA":"NYY", "SDN":"SD", "CHN":"CHC", "SLN":"STL", "SFN":"SF", "LAN":"LAD", "TBA":"TB", "KCA":"KC", "CHA":"CWS", "ANA":"LAA", "NYN":"NYM"}, inplace=True)

In [ ]:
# Adding a prior year column in order to match last seasons stats from pitching_df/team_stats to game_df
game_df['prior_year'] = game_df['New_Date'].dt.year-1

Merge pitching_df stats to game_df

In [ ]:
# Merging the pitching stats on the prior year in the game_df in order to leverage the pitchers
# Doing it twice for home & away starting pitchers
game_df = game_df.merge(pitching_df, how='left', left_on=['prior_year','VisitorStartingPitcherName'], right_on=['year', 'playerName'])
game_df = game_df.merge(pitching_df, how='left', left_on=['prior_year','HomeStartingPitcherName'], right_on=['year', 'playerName'])

Merge team batting stats to game_df

In [ ]:
# Dropping redundant columns from batting stats df
team_stats.drop('plateAppearances', axis=1, inplace=True)

In [ ]:
# Merging away team stats
game_df = game_df.merge(team_stats, how='left', left_on=['prior_year', 'VisitingTeam'], 
                        right_on=['year', 'teamAbbrev'], suffixes=('', '_away'))

# Merging home team stats
game_df = game_df.merge(team_stats, how='left', left_on=['prior_year', 'HomeTeam'], 
                        right_on=['year', 'teamAbbrev'], suffixes=('', '_home'))

# Creating an integer reference point in game_df
game_df['current_year'] = game_df['New_Date'].dt.year

In [ ]:
# Addressing NaN values in game_df by giving them a -1 score
# NaN indicates that the player did not have stats from the prior year to measure against
game_df.fillna(value = -1, inplace=True)

In [ ]:
# Checking game_df for ANY NaN values
game_df.isnull().values.any()
# Returns false, indicating that there are NO NaN values in the game_df

False

In [ ]:
game_df.to_csv('Clean_MLB_Data.csv')